### ISSUE TITLE
Doesn't work with closed source

### ISSUE THREAD

**Issue by john-warpdevelopment** [fpigerre/IssuesDownload#2]
Could it be that it doesn't work with closed source repo's ? Previously I had a tool that asked username and password to accommodate those repos.

**Comment by fpigerre** [comment]
Hello @john-warpdevelopment!

If an authentication token is entered inside the IssuesDownload.properties file and placed in the same directory as instructed in the README.md file, IssuesDownload should be able to access private repositories.

Thankyou,
psgs :palm_tree:
